### ISSUE TITLE
Can't find configurationAddr signature sometimes

### ISSUE THREAD

**Issue by TheEZIC** [KotRikD/tosu#164] opened 2024-07-08 22:58 UTC
When I used this program in debug mode I found this issue. It happens very rarely. It's seems like tosu somehow finds wrong address when scans for configurationAddr and then returns low address value.

![image](https://github.com/KotRikD/tosu/assets/35061249/497a9107-b113-49a3-9a06-842fffaf36a0)

**Comment by cyperdark** [comment] 2024-07-08 23:10
@KotRikD

**Comment by TheEZIC** [comment] 2024-07-09 00:21
It's seems like KuinaTheFox [had](https://discord.com/channels/1056534107330445362/1185957776665628764/1253454810926026855) the same issue. But I don't know whether it connected to this issue.
![image](https://github.com/KotRikD/tosu/assets/35061249/4901d92f-6344-4873-8eb2-7fac028d9c77)

**Comment by cyperdark** [comment] 2024-07-14 04:52
ah, shit why always read some portion of message, so if you see DEBUGERROR with pink/purple, thats means it tried to read and failed, but it's okay until it's not spamming ERROR with red

**Comment by cyperdark** [comment] 2024-08-08 05:20
closing for now, because config some breaks in unknown state, about others i dont know, plus since then many things changed and need reproduction with logs to see what exactly wrong

**Closed by cyperdark** 2024-08-08 05:20 UTC
Labels: memory
